### PR TITLE
Add shape options

### PR DESCRIPTION
**Pull request by techlemur**
Looks for shape option field in nodes.  Can be 'sphere' or 'box', defaults to sphere.

### CODE REVIEW

**Comment by AmbroiseCouissin** [comment]
What about cylinders? ;)
https://threejs.org/docs/#api/geometries/CylinderGeometry

**Comment by techlemur** [comment]
I'll add cylinders next time I have the project open.

**Comment by vasturiano** [comment]
Thanks for the PR @techlemur. Since `v1.16.0` any custom geometry/object can be specified as node representation instead of the default spheres.

This is done using the `nodeThreeObject` property. For example, to use red cubes with volume proportional to the node's value:
```
Graph.nodeThreeObject(d => new THREE.Mesh(
          new THREE.BoxGeometry(Math.cbrt(d.value), Math.cbrt(d.value), Math.cbrt(d.value)),
          new THREE.MeshLambertMaterial({ color: 0xFF0000 })
));
```

Here's a [demo example](https://github.com/vasturiano/3d-force-graph/blob/master/example/custom-node-geometry/index.html) using various shapes:
https://vasturiano.github.io/3d-force-graph/example/custom-node-geometry/

Let me know if this solves your use case.

**Comment by techlemur** [comment]
Yep, that solves it.  Thanks!  Turns out I was working with code from v1.12.  My bad.

**Pull request closed without merging**
